name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Go App and Create Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          cd services/dashboard-service
          ./bin/build
          cp dist/linux-amd64 ../../k8s/dashboard-service
          cd ../../k8s/dashboard-service
          docker build -t baghelg/dashboard-service:0.0.4 .

      - name: Log into Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: docker push baghelg/dashboard-service:0.0.4
